<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-20T18:00:55 IST" name="Default suite" finished-at="2025-10-20T18:01:09 IST" duration-ms="14865">
    <groups>
    </groups>
    <test started-at="2025-10-20T18:00:55 IST" name="Default test" finished-at="2025-10-20T18:01:09 IST" duration-ms="14865">
      <class name="CognizantTestngPractice.OrangeHrmExample">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:CognizantTestngPractice.OrangeHrmExample@4116aac9]" started-at="2025-10-20T18:00:55 IST" name="beforeClass" finished-at="2025-10-20T18:01:00 IST" duration-ms="5855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="signup()[pri:0, instance:CognizantTestngPractice.OrangeHrmExample@4116aac9]" started-at="2025-10-20T18:01:00 IST" name="signup" finished-at="2025-10-20T18:01:02 IST" duration-ms="2008" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/inde] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/inde] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at CognizantTestngPractice.OrangeHrmExample.signup(OrangeHrmExample.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup -->
        <test-method signature="FailedLoginException()[pri:0, instance:CognizantTestngPractice.OrangeHrmExample@4116aac9]" started-at="2025-10-20T18:01:02 IST" name="FailedLoginException" finished-at="2025-10-20T18:01:02 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailedLoginException -->
        <test-method signature="Login()[pri:0, instance:CognizantTestngPractice.OrangeHrmExample@4116aac9]" started-at="2025-10-20T18:01:02 IST" name="Login" finished-at="2025-10-20T18:01:02 IST" depends-on-methods="CognizantTestngPractice.OrangeHrmExample.signup" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CognizantTestngPractice.OrangeHrmExample.Login() on instance CognizantTestngPractice.OrangeHrmExample@4116aac9 depends on not successfully finished methods 
[CognizantTestngPractice.OrangeHrmExample.signup() on instance CognizantTestngPractice.OrangeHrmExample@4116aac9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CognizantTestngPractice.OrangeHrmExample.Login() on instance CognizantTestngPractice.OrangeHrmExample@4116aac9 depends on not successfully finished methods 
[CognizantTestngPractice.OrangeHrmExample.signup() on instance CognizantTestngPractice.OrangeHrmExample@4116aac9]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="Final()[pri:0, instance:CognizantTestngPractice.OrangeHrmExample@4116aac9]" started-at="2025-10-20T18:01:02 IST" name="Final" finished-at="2025-10-20T18:01:09 IST" duration-ms="6943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Final -->
      </class> <!-- CognizantTestngPractice.OrangeHrmExample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
